"""empty message

Revision ID: 0cdc04720456
Revises: 56866ac92ec2
Create Date: 2022-07-31 10:07:30.501327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdc04720456'
down_revision = '56866ac92ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbtrialapi', sa.Column('kota', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbtrialapi', 'kota')
    # ### end Alembic commands ###
