"""empty message

Revision ID: 2cc7f5b5af32
Revises: cc00561666b2
Create Date: 2022-02-18 01:46:43.081492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc7f5b5af32'
down_revision = 'cc00561666b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbcust',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custname', sa.String(length=60), nullable=True),
    sa.Column('custadd', sa.String(length=60), nullable=True),
    sa.Column('custtel', sa.String(length=15), nullable=True),
    sa.Column('custjoin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbcust')
    # ### end Alembic commands ###
