"""empty message

Revision ID: 56866ac92ec2
Revises: 7123ab83aafe
Create Date: 2022-05-08 14:02:22.435554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56866ac92ec2'
down_revision = '7123ab83aafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbtrialapi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbtrialapi')
    # ### end Alembic commands ###
