"""empty message

Revision ID: 7123ab83aafe
Revises: ffb0c268489d
Create Date: 2022-02-18 18:55:36.034535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7123ab83aafe'
down_revision = 'ffb0c268489d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbservice', sa.Column('custid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbservice', 'custid')
    # ### end Alembic commands ###
