"""empty message

Revision ID: 90e0e2fcdff7
Revises: db70e28f09f5
Create Date: 2022-02-16 17:24:46.304234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e0e2fcdff7'
down_revision = 'db70e28f09f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercdp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercdp')
    # ### end Alembic commands ###
