"""empty message

Revision ID: cc00561666b2
Revises: 90e0e2fcdff7
Create Date: 2022-02-17 15:17:54.647587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc00561666b2'
down_revision = '90e0e2fcdff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercdp', sa.Column('password', sa.String(length=60), nullable=True))
    op.add_column('usercdp', sa.Column('username', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'usercdp', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usercdp', type_='unique')
    op.drop_column('usercdp', 'username')
    op.drop_column('usercdp', 'password')
    # ### end Alembic commands ###
