"""empty message

Revision ID: ffb0c268489d
Revises: 2cc7f5b5af32
Create Date: 2022-02-18 17:57:56.580496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb0c268489d'
down_revision = '2cc7f5b5af32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicedate', sa.Date(), nullable=True),
    sa.Column('keluhan', sa.String(length=120), nullable=True),
    sa.Column('tindakan', sa.String(length=120), nullable=True),
    sa.Column('hasil', sa.String(length=120), nullable=True),
    sa.Column('dokumentasi', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbservice')
    # ### end Alembic commands ###
